# app/config/main_paths.yaml

# ğŸ“„ CSVãƒ•ã‚¡ã‚¤ãƒ«é–¢é€£ãƒ‘ã‚¹
csv:
    receive_header_definition: 'config/input_header_info.csv' # ç¨®åˆ¥åˆ¤å®šç”¨ãƒ˜ãƒƒãƒ€ãƒ¼
    required_columns_definition: 'config/required_columns_definition.csv' # å¿…é ˆã‚«ãƒ©ãƒ ã®å®šç¾©
    expected_dtypes: 'config/expected_dtypes.json' # ãƒ‡ãƒ¼ã‚¿å‹ã®æœŸå¾…å®šç¾©
    unit_price_table: '/work/app/data/master/unit_price_table.csv' # å˜ä¾¡

# # excelãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆãƒ‘ã‚¹
# excel:
#     manage_template_path: 'data/master/abc_average_write_targets.csv'

# ğŸ“ ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªæ§‹æˆ
directories:
    output: 'app/data/output' # å‡ºåŠ›çµæœã®ä¿å­˜å…ˆ
    master_data: 'app/data/master' # ãƒã‚¹ã‚¿ãƒ¼CSVã®æ ¼ç´å ´æ‰€
    template: 'app/data/template'
    temp: 'app/data/temp' # ä¸€æ™‚ãƒ•ã‚¡ã‚¤ãƒ«æ ¼ç´

# ğŸ“œ ãƒ­ã‚°è¨­å®š
logs:
    app: 'logs/app.log'
    error: 'logs/error.log'
    debug: 'logs/debug.log'

# yamlãƒ‘ã‚¹
config_files:
    app_config: 'config/app_config.yaml'
    expected_dtypes: 'config/expected_import_csv_dtypes.yaml'
    page_config: 'config/page_config.yaml'
    templates_config: 'config/templates_config.yaml'
    csv_sources_config: 'config/csv_sources_config.yaml'
    required_columns_definition: 'config/required_columns_definition.yaml'
