# app/config/main_paths.yaml

# ğŸ“„ CSVãƒ•ã‚¡ã‚¤ãƒ«é–¢é€£ãƒ‘ã‚¹
csv:
    receive_header_definition: 'data/master/receive_header_definition.csv' # ç¨®åˆ¥åˆ¤å®šç”¨ãƒ˜ãƒƒãƒ€ãƒ¼
    required_columns_definition: 'config/required_columns_definition.csv' # å¿…é ˆã‚«ãƒ©ãƒ ã®å®šç¾©
    expected_dtypes: 'config/expected_dtypes.json' # ãƒ‡ãƒ¼ã‚¿å‹ã®æœŸå¾…å®šç¾©
    unit_price_table: 'data/master/costs/unit_price_table.csv'
    transport_costs: 'data/master/costs/transport_costs.csv' #

# # excelãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆãƒ‘ã‚¹
# excel:
#     manage_template_path: 'data/master/abc_average_write_targets.csv'

# ğŸ“ ãƒ‡ã‚£ãƒ¬ã‚¯ãƒˆãƒªæ§‹æˆ
directories:
    input: 'data/input'
    output: 'data/output' # å‡ºåŠ›çµæœã®ä¿å­˜å…ˆ
    master_data: 'data/master' # ãƒã‚¹ã‚¿ãƒ¼CSVã®æ ¼ç´å ´æ‰€
    template: 'data/template'
    temp: 'data/temp' # ä¸€æ™‚ãƒ•ã‚¡ã‚¤ãƒ«æ ¼ç´
    models:
        models: 'data/models' # ãƒ¢ãƒ‡ãƒ«ã®ä¿å­˜å…ˆ
        predicted_import_volume: 'data/models/predicted_import_volume' # äºˆæ¸¬æ¬å…¥é‡ã®ä¿å­˜å…ˆ

# ğŸ“œ ãƒ­ã‚°è¨­å®š
logs:
    app: 'logs/app.log'
    error: 'logs/error.log'
    debug: 'logs/debug.log'

# yamlãƒ‘ã‚¹
config_files:
    app_config: 'config/app_config.yaml'
    expected_dtypes: 'config/expected_import_csv_dtypes.yaml'
    page_config: 'config/page_config.yaml'
    templates_config: 'config/templates_config.yaml'
    csv_sources_config: 'config/csv_sources_config.yaml'
    required_columns_definition: 'config/required_columns_definition.yaml'
    factory_manage_menu_config: '/work/app/config/factory_manage/menu_config.yaml'

# SQLãƒ‡ãƒ¼ã‚¿ãƒ™ãƒ¼ã‚¹ãƒ‘ã‚¹
sql_database:
    weight_data: '/work/app/data/factory_manage/weight_data.db'
