pages:
    - label: ãƒˆãƒƒãƒ—ãƒšãƒ¼ã‚¸
      title: ãƒˆãƒƒãƒ—ãƒšãƒ¼ã‚¸
      id: home
      function: render_home
      addons: true

    - label: ç®¡ç†æ¥­å‹™
      title: å¸³ç¥¨ä½œæˆ
      id: manage_work
      function: manage_work_controller

    - label: å·¥å ´ç®¡ç†
      title: å·¥å ´ç®¡ç†
      id: factory_manage
      function: factory_manage_work_controller

    - label: å‚è¬€ãã‚“NAVI
      title: å‚è¬€ãã‚“NAVI
      id: sanbo_navi
      function: sanbo_navi

    - label: ä¾¿åˆ©ãƒ„ãƒ¼ãƒ«
      title: ä¾¿åˆ©ãƒ„ãƒ¼ãƒ«
      id: util
      function: render_util_page
      # message: 'ğŸ“¥ ã‚„ã‚ˆã„ä¼šè¨ˆã‚¤ãƒ³ãƒãƒ¼ãƒˆæ©Ÿèƒ½ã¯ç¾åœ¨æº–å‚™ä¸­ã§ã™ã€‚'

    - label: æ©Ÿèƒ½ï¼’
      title: æ©Ÿèƒ½ï¼’
      id: feature2
      message: 'ğŸ§ª æ–°æ©Ÿèƒ½ï¼’ã¯ä»Šå¾Œè¿½åŠ äºˆå®šã§ã™ã€‚ã—ã°ã‚‰ããŠå¾…ã¡ãã ã•ã„ã€‚'

    # - id: home
    #   label: ãƒ›ãƒ¼ãƒ 
    #   function: render_home
